/* 静态预览用户目录 —— id === 'me' 为当前登录用户 */
window.LingDaUsers = {
  ME_ID: 'me',
  list: {
    me: {
      id: 'me',
      name: '开发预览',
      av: '开',
      avClass: 'av-indigo',
      tag: '认证学生',
      tagClass: 'tag-sky',
      college: '新闻学院',
      major: '前端',
      grade: '研一',
      bio: '仅用于本地 UI 开发预览',
      rating: '4.9',
      teams: 8,
      posts: 3,
    },
    jiaowu: {
      id: 'jiaowu',
      name: '教务处',
      av: '官',
      avClass: 'av-indigo',
      tag: '官方',
      tagClass: 'tag-teal',
      college: '学校官方',
      major: '教务管理',
      grade: '—',
      bio: '发布选课、考试与培养方案相关通知。',
      rating: '5.0',
      teams: 0,
      posts: 26,
    },
    photo: {
      id: 'photo',
      name: '摄影协会',
      av: '社',
      avClass: 'av-amber',
      tag: '社团',
      tagClass: 'tag-amber',
      college: '校级社团',
      major: '摄影',
      grade: '—',
      bio: '热爱光影，周末外拍常有，新手友好。',
      rating: '4.8',
      teams: 12,
      posts: 41,
    },
    lin: {
      id: 'lin',
      name: '小林',
      av: '林',
      avClass: 'av-sky',
      tag: '认证学生',
      tagClass: 'tag-sky',
      college: '理学院',
      major: '数学',
      grade: '大二',
      bio: '高数进度党，常去二教自习。',
      rating: '4.7',
      teams: 5,
      posts: 7,
    },
    chen: {
      id: 'chen',
      name: '陈同学',
      av: '陈',
      avClass: 'av-teal',
      tag: '认证学生',
      tagClass: 'tag-sky',
      college: '经管学院',
      major: '会计',
      grade: '大三',
      bio: '乐于助人，校园失物总会捡到。',
      rating: '4.9',
      teams: 4,
      posts: 9,
    },
    zhou: {
      id: 'zhou',
      name: '周一凡',
      av: '周',
      avClass: 'av-sky',
      tag: '认证学生',
      tagClass: 'tag-sky',
      college: '工学院',
      major: '车辆工程',
      grade: '大四',
      bio: '早班机场拼车达人，准时靠谱。',
      rating: '4.9',
      teams: 12,
      posts: 3,
    },
    su: {
      id: 'su',
      name: '苏晴',
      av: '苏',
      avClass: 'av-indigo',
      tag: '认证学生',
      tagClass: 'tag-sky',
      college: '外语学院',
      major: '英语',
      grade: '研一',
      bio: '周末返乡拼车，聊天不冷场。',
      rating: '4.8',
      teams: 8,
      posts: 2,
    },
    he: {
      id: 'he',
      name: '何然',
      av: '何',
      avClass: 'av-teal',
      tag: '认证学生',
      tagClass: 'tag-sky',
      college: '信息学院',
      major: '软件工程',
      grade: '大三',
      bio: '南站出发拼车次数 21，五星好评。',
      rating: '5.0',
      teams: 21,
      posts: 5,
    },
    ye: {
      id: 'ye',
      name: '叶舟',
      av: '叶',
      avClass: 'av-amber',
      tag: '认证学生',
      tagClass: 'tag-sky',
      college: '信息学院',
      major: '计科',
      grade: '大二',
      bio: '王者 / Steam 开黑，氛围型选手。',
      rating: '4.7',
      teams: 9,
      posts: 6,
    },
    xia: {
      id: 'xia',
      name: '夏沫',
      av: '夏',
      avClass: 'av-rose',
      tag: '认证学生',
      tagClass: 'tag-sky',
      college: '艺术学院',
      major: '设计',
      grade: '大三',
      bio: '剧本杀 / 桌游，组局必备。',
      rating: '4.9',
      teams: 6,
      posts: 4,
    },
    cheng: {
      id: 'cheng',
      name: '程思',
      av: '程',
      avClass: 'av-teal',
      tag: '认证学生',
      tagClass: 'tag-sky',
      college: '信息学院',
      major: '算法',
      grade: '研二',
      bio: '考研数学 / 算法组队，效率优先。',
      rating: '5.0',
      teams: 15,
      posts: 11,
    },
    fang: {
      id: 'fang',
      name: '方圆',
      av: '方',
      avClass: 'av-violet',
      tag: '认证学生',
      tagClass: 'tag-sky',
      college: '外语学院',
      major: '英语',
      grade: '大四',
      bio: '六级冲刺搭子，晨读夜练。',
      rating: '4.8',
      teams: 7,
      posts: 3,
    },
    li: {
      id: 'li',
      name: '李想',
      av: '李',
      avClass: 'av-sky',
      tag: '认证学生',
      tagClass: 'tag-sky',
      college: '法学院',
      major: '法学',
      grade: '大一',
      bio: '关注选课与培养方案。',
      rating: '4.6',
      teams: 1,
      posts: 2,
    },
    wang: {
      id: 'wang',
      name: '王同学',
      av: '王',
      avClass: 'av-amber',
      tag: '认证学生',
      tagClass: 'tag-sky',
      college: '工学院',
      major: '机械',
      grade: '大二',
      bio: '课表党，试运行准时在线。',
      rating: '4.5',
      teams: 2,
      posts: 1,
    },
    zhouzhou: {
      id: 'zhouzhou',
      name: '周周',
      av: '周',
      avClass: 'av-violet',
      tag: '认证学生',
      tagClass: 'tag-sky',
      college: '艺术学院',
      major: '摄影',
      grade: '大二',
      bio: '摄影协会积极分子，爱夜景。',
      rating: '4.7',
      teams: 4,
      posts: 8,
    },
    han: {
      id: 'han',
      name: '韩梅',
      av: '韩',
      avClass: 'av-rose',
      tag: '认证学生',
      tagClass: 'tag-sky',
      college: '经管学院',
      major: '金融',
      grade: '大三',
      bio: '热心肠，失物招领常转发。',
      rating: '4.8',
      teams: 3,
      posts: 4,
    },
    announce: {
      id: 'announce',
      name: '平台运营',
      av: '公',
      avClass: 'av-amber',
      tag: '官方',
      tagClass: 'tag-teal',
      college: '灵搭官方',
      major: '运营',
      grade: '—',
      bio: '平台公告与活动运营账号。',
      rating: '5.0',
      teams: 0,
      posts: 18,
    },
    ops: {
      id: 'ops',
      name: '运维值班',
      av: '运',
      avClass: 'av-sky',
      tag: '官方',
      tagClass: 'tag-teal',
      college: '灵搭官方',
      major: '运维',
      grade: '—',
      bio: '负责系统维护与故障通知。',
      rating: '5.0',
      teams: 0,
      posts: 9,
    },
    school: {
      id: 'school',
      name: '校园服务',
      av: '校',
      avClass: 'av-teal',
      tag: '官方',
      tagClass: 'tag-teal',
      college: '后勤 / 校车',
      major: '校园服务',
      grade: '—',
      bio: '校车、食堂、场馆等校园服务资讯。',
      rating: '5.0',
      teams: 0,
      posts: 14,
    },
  },
  get: function (id) {
    return this.list[id] || null;
  },
  isSelf: function (id) {
    return !id || id === this.ME_ID;
  },
};
