/**
 * 错误码与 docs/API.md §0.7 保持一致。
 * 任何新增码必须同步更新 docs/API.md。
 */
export const ERROR_CODES = {
  SUCCESS: 0,

  // 通用
  UNAUTHORIZED: 10001,
  FORBIDDEN: 10002,
  VALIDATION_FAILED: 10003,
  ACCOUNT_RESTRICTED: 10004,
  TOO_MANY_REQUESTS: 10005,

  // Auth
  USER_ID_TAKEN: 11001,
  INVALID_CREDENTIALS: 11002,

  // 资源
  NOT_FOUND: 20001,

  // 房间 / 成员
  ROOM_FULL: 30001,
  ROOM_EXPIRED: 30002,
  DUPLICATE_APPLY: 30003,
  NOT_ROOM_OWNER: 30004,
  ROOM_NOT_COMPLETED: 30005,
  DUPLICATE_EVALUATION: 30006,
  WRONG_JOIN_PASSWORD: 30007,

  // 社交
  BLOCKED_BY_TARGET: 40001,
  DUPLICATE_FRIEND_REQUEST: 40002,

  // 服务器
  INTERNAL_ERROR: 99999,
} as const;

export const ERROR_MESSAGES: Record<number, string> = {
  [ERROR_CODES.SUCCESS]: 'ok',
  [ERROR_CODES.UNAUTHORIZED]: '未登录或登录已失效',
  [ERROR_CODES.FORBIDDEN]: '无权限',
  [ERROR_CODES.VALIDATION_FAILED]: '参数校验失败',
  [ERROR_CODES.ACCOUNT_RESTRICTED]: '账号已被限制或封禁',
  [ERROR_CODES.TOO_MANY_REQUESTS]: '请求过于频繁，请稍后再试',
  [ERROR_CODES.USER_ID_TAKEN]: '学号或手机号已注册',
  [ERROR_CODES.INVALID_CREDENTIALS]: '学号或密码错误',
  [ERROR_CODES.NOT_FOUND]: '资源不存在',
  [ERROR_CODES.ROOM_FULL]: '房间已满',
  [ERROR_CODES.ROOM_EXPIRED]: '房间已过期或已结束',
  [ERROR_CODES.DUPLICATE_APPLY]: '重复申请',
  [ERROR_CODES.NOT_ROOM_OWNER]: '仅房主可操作',
  [ERROR_CODES.ROOM_NOT_COMPLETED]: '房间未完成,暂不可评价',
  [ERROR_CODES.DUPLICATE_EVALUATION]: '重复评价',
  [ERROR_CODES.WRONG_JOIN_PASSWORD]: '加入口令错误',
  [ERROR_CODES.BLOCKED_BY_TARGET]: '已被对方拉黑,无法操作',
  [ERROR_CODES.DUPLICATE_FRIEND_REQUEST]: '请求已存在或已是好友',
  [ERROR_CODES.INTERNAL_ERROR]: '服务器内部错误',
};
